apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  username: base64encoded-username  # use base64 encoding for values
  password: base64encoded-password  # use base64 encoding for values
