name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      ECR_REPOSITORY_BACKEND: mini-pastebin-repo:backend
      ECR_REPOSITORY_FRONTEND: mini-pastebin-repo:frontend
      AWS_REGION: ${{ secrets.AWS_REGION }}
      CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (to build multi-platform images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to AWS ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      # Step 4: Build, Tag, and Push the Backend Docker image
      - name: Build and push backend Docker image
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND -f ./backend/Dockerfile ./backend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND

      # Step 5: Build, Tag, and Push the Frontend Docker image
      - name: Build and push frontend Docker image
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND -f ./frontend/Dockerfile ./frontend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND

      # Step 6: Set up kubectl
      - name: Set up kubectl
        run: |
          echo ${{ secrets.KUBECONFIG_DATA }} | base64 --decode > ~/.kube/config
          kubectl config use-context arn:aws:eks:${{ secrets.AWS_REGION }}:345594564536:cluster/${{ secrets.EKS_CLUSTER_NAME }}

      # Step 7: Update Backend Deployment in EKS
      - name: Deploy backend to EKS
        run: |
          kubectl set image deployment/backend-deployment backend=$ECR_REGISTRY/$ECR_REPOSITORY_BACKEND --record

      # Step 8: Update Frontend Deployment in EKS
      - name: Deploy frontend to EKS
        run: |
          kubectl set image deployment/frontend-deployment frontend=$ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND --record

